schema_version = 1
name = 'template'

[services]
[services.main]
architecture = ''
run_as_user = 10001
run_as_group = 0
fs_group = 0
read_only_root_filesystem = false
working_dir = ''
termination_grace_seconds = 0
certificate_mounts = []
mounts = []
temporary_mounts = []
image = 'pgsty/minio:RELEASE.2026-06-18T00-00-00Z@sha256:dacff8306a6e0a734518533992dbdcca26bc1ca47f77cf47cb9945725f92b29b'
port = 9000
public_tcp = []
public = false
size = 'large'
replicas = 1
update_strategy = ''
healthcheck = '/minio/health/live'
command = []
args = ['server', '/data', '--console-address', ':9001']
depends_on = []
networks = ['default']
restart_nonce = ''
registry_credential = ''
aws_identity = ''

[services.main.volume]
mount_path = '/data'
size_gib = 5
storage_class = ''

[[services.main.ports]]
name = 'console'
port = 9001
target_port = 9001
protocol = 'TCP'

[services.main.env]
MINIO_BROWSER_REDIRECT = 'false'
MINIO_ROOT_USER = 'hakopod'

[services.main.secrets]
[services.main.secrets.MINIO_ROOT_PASSWORD]
ref = 'root-password'

[networks]
[networks.default]
internal = false
virtual_network = ''
segment = ''
