schema_version = 1
name = 'template'

[services]
[services.main]
architecture = ''
run_as_user = 1001
run_as_group = 0
fs_group = 0
read_only_root_filesystem = false
working_dir = ''
termination_grace_seconds = 0
certificate_mounts = []
mounts = []
temporary_mounts = []
image = 'adrianmusante/pocketbase:latest@sha256:8017b8d26ad63104b9ed5209f542ed40a4179aab17c00a67a8d6bbd76fc29954'
port = 8090
public_tcp = []
ports = []
public = true
size = 'medium'
replicas = 1
update_strategy = ''
healthcheck = '/api/health'
command = []
args = []
depends_on = []
networks = ['default']
restart_nonce = ''
registry_credential = ''
aws_identity = ''

[services.main.volume]
mount_path = '/pocketbase'
size_gib = 5
storage_class = ''

[services.main.env]
POCKETBASE_ADMIN_EMAIL = '{{config.admin-email}}'
POCKETBASE_ADMIN_UPSERT = 'true'
POCKETBASE_PORT_NUMBER = '8090'

[services.main.secrets]
[services.main.secrets.POCKETBASE_ADMIN_PASSWORD]
ref = 'admin-password'

[networks]
[networks.default]
internal = false
virtual_network = ''
segment = ''
