schema_version = 1
name = 'template'

[services]
[services.bytebase]
architecture = ''
run_as_user = 0
run_as_group = 0
fs_group = 0
read_only_root_filesystem = false
working_dir = ''
termination_grace_seconds = 0
certificate_mounts = []
temporary_mounts = []
image = 'bytebase/bytebase:3.3.0'
port = 8080
public_tcp = []
ports = []
public = true
size = 'medium'
replicas = 1
update_strategy = ''
healthcheck = ''
command = []
args = []
depends_on = ['bytebase-db']
networks = ['default']
restart_nonce = ''
registry_credential = ''
aws_identity = ''

[[services.bytebase.mounts]]
volume = 'data'
mount_path = '/var/opt/bytebase'
read_only = false
sub_path = ''

[services.bytebase.env]
[services.bytebase.secrets]
[services.bytebase.secrets.PG_URL]
ref = 'pg-url'

[services.bytebase-db]
architecture = ''
run_as_user = 0
run_as_group = 0
fs_group = 0
read_only_root_filesystem = false
working_dir = ''
termination_grace_seconds = 0
certificate_mounts = []
temporary_mounts = []
image = 'postgres:13@sha256:4689940c683801b4ab839ab3b0a0a3555a5fe425371422310944e89eca7d8068'
port = 5432
public_tcp = []
ports = []
public = false
size = 'medium'
replicas = 1
update_strategy = ''
healthcheck = ''
command = []
args = []
depends_on = []
networks = ['default']
restart_nonce = ''
registry_credential = ''
aws_identity = ''

[[services.bytebase-db.mounts]]
volume = 'db-data'
mount_path = '/var/lib/postgresql/data'
read_only = false
sub_path = ''

[services.bytebase-db.env]
POSTGRES_DB = 'bytebase'
POSTGRES_USER = 'postgres'

[services.bytebase-db.secrets]
[services.bytebase-db.secrets.POSTGRES_PASSWORD]
ref = 'postgres-password'

[networks]
[networks.default]
internal = false
virtual_network = ''
segment = ''

[volumes]
[volumes.data]
size_gib = 5
storage_class = ''
access_mode = 'ReadWriteOnce'

[volumes.db-data]
size_gib = 5
storage_class = ''
access_mode = 'ReadWriteOnce'
